name: Docs

on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "."
        pre-build-command: "apt-get update -y && apt-get install -y cmake g++ capnproto pkg-config && pip install -r requirements.txt"
        build-command: "sphinx-multiversion docs build/html"
